/**
 * Validate report form data
 * @param {Object} formData - The report form data
 * @param {number} step - The current step (1-4)
 * @returns {Object} - { isValid: boolean, errors: Object }
 */
export const validateReportForm = (formData, step) => {
  const errors = {};

  // Step 1: Basic information
  if (step === 1) {
    if (!formData.title?.trim()) {
      errors.title = 'Report title is required';
    }
    
    if (!formData.clientName?.trim()) {
      errors.clientName = 'Client name is required';
    }
    
    // Validate property address fields if any are filled in
    const addressFields = Object.values(formData.propertyAddress || {});
    const hasPartialAddress = addressFields.some(field => field && field !== 'USA');
    const allRequiredFieldsPresent = formData.propertyAddress?.street?.trim() && 
                                     formData.propertyAddress?.city?.trim() && 
                                     formData.propertyAddress?.state?.trim() && 
                                     formData.propertyAddress?.zipCode?.trim();
    
    if (hasPartialAddress && !allRequiredFieldsPresent) {
      errors.propertyAddress = 'Please complete all address fields or leave them all empty';
    }
    
    // Validate inspection date
    if (!formData.inspectionDate) {
      errors.inspectionDate = 'Inspection date is required';
    }
  }
  
  // Step 2: Photos
  // Photo validation would typically happen in the PhotoUploadStep component
  
  // Step 3: AI Analysis
  if (step === 3) {
    // No strict validation requirements for summary or damages
    // These are typically generated by AI
  }
  
  // Step 4: Review
  if (step === 4) {
    // Final validation before submission
    if (!formData.title?.trim()) {
      errors.title = 'Report title is required';
    }
    
    if (!formData.clientName?.trim()) {
      errors.clientName = 'Client name is required';
    }
    
    if (!formData.inspectionDate) {
      errors.inspectionDate = 'Inspection date is required';
    }
  }
  
  return {
    isValid: Object.keys(errors).length === 0,
    errors
  };
};

/**
 * Get form error message for display
 * @param {Object} errors - Error object from validateReportForm
 * @returns {string} - Formatted error message
 */
export const getFormErrorMessage = (errors) => {
  if (!errors || Object.keys(errors).length === 0) {
    return '';
  }
  
  // Return the first error message
  const firstError = Object.values(errors)[0];
  return firstError;
}; 